version: '3'
services:
  postgres:
    container_name: catalog-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=catalog
    ports:
      - "5432:5432"