version: '3'
services:
  postgres:
    container_name: user-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
    ports:
      - "5436:5432"

